import { chromium } from 'playwright'
const BASE = (process.env.BASE_URL ?? 'http://localhost:3100').replace(/\/$/, '')
const OUT = process.env.OUT!
const W = Number(process.env.W ?? 375)
async function main() {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' }).catch(() => chromium.launch({ headless: true }))
  const ctx = await browser.newContext({ viewport: { width: W, height: 812 }, deviceScaleFactor: W < 700 ? 2 : 1, isMobile: W < 700 })
  const page = await ctx.newPage()
  const clip = async (name: string, y = 0, h = 1300) => page.screenshot({ path: `${OUT}/${name}-${W}.png`, fullPage: true, clip: { x: 0, y, width: W, height: h } })
  await page.goto(`${BASE}/landing`, { waitUntil: 'networkidle' })
  await clip('landing')
  await page.goto(`${BASE}/demo`, { waitUntil: 'networkidle' })
  await clip('job-top')
  const funnel = page.getByText('connections screened').first()
  const box = await funnel.boundingBox()
  const sy = (await page.evaluate(() => window.scrollY)) + (box?.y ?? 0)
  await clip('job-funnel', Math.max(0, sy - 200), 1300)
  await page.locator('summary', { hasText: /not recommended/i }).click()
  const weak = await page.locator('summary', { hasText: /not recommended/i }).boundingBox()
  const wy = (await page.evaluate(() => window.scrollY)) + (weak?.y ?? 0)
  await clip('job-weaker', Math.max(0, wy - 100), 1300)
  await page.getByRole('link', { name: /outreach draft|draft outreach/i }).first().click()
  await page.waitForURL(/\/messages\//); await page.waitForLoadState('networkidle')
  await clip('workspace', 0, 1500)
  const drafts = await page.getByRole('heading', { name: 'Drafts' }).boundingBox()
  const dy = (await page.evaluate(() => window.scrollY)) + (drafts?.y ?? 0)
  await clip('workspace-drafts', Math.max(0, dy - 50), 1300)
  await page.getByRole('link', { name: /view profile/i }).click()
  await page.waitForURL(/\/contacts\//); await page.waitForLoadState('networkidle')
  await clip('contact', 0, 1000)
  await page.goto(`${BASE}/demo/exit`)
  await browser.close()
}
main().catch(e => { console.error(e); process.exit(1) })
